- link:
    ~/.wslconfig:
        path: config/wsl/.wslconfig
        force: true
        create: true

- plugins:
    - lib/dotbot-plugins/dotbot-windows/dotbot_windows.py

- windows:
    fonts:
      path: "fonts/"
